// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1dOqNO6RgF_-LRrFKyoiH0ZBv7pb13hQ',
    appId: '1:590884738429:web:d27f6dbf0ed54efae6a814',
    messagingSenderId: '590884738429',
    projectId: 'itransit-2-99b65',
    authDomain: 'itransit-2-99b65.firebaseapp.com',
    storageBucket: 'itransit-2-99b65.firebasestorage.app',
    measurementId: 'G-7MPH3TJVNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgvg9pJaZJZ80_yHfrWquah5IJOeOigJU',
    appId: '1:590884738429:android:e03dbc7b4ed48fcce6a814',
    messagingSenderId: '590884738429',
    projectId: 'itransit-2-99b65',
    storageBucket: 'itransit-2-99b65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO93h1aDmFK8TyE7RIHc-YLr-DWNdpiG8',
    appId: '1:590884738429:ios:2ac7a0d56c321adae6a814',
    messagingSenderId: '590884738429',
    projectId: 'itransit-2-99b65',
    storageBucket: 'itransit-2-99b65.firebasestorage.app',
    iosBundleId: 'com.example.itransit2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO93h1aDmFK8TyE7RIHc-YLr-DWNdpiG8',
    appId: '1:590884738429:ios:2ac7a0d56c321adae6a814',
    messagingSenderId: '590884738429',
    projectId: 'itransit-2-99b65',
    storageBucket: 'itransit-2-99b65.firebasestorage.app',
    iosBundleId: 'com.example.itransit2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1dOqNO6RgF_-LRrFKyoiH0ZBv7pb13hQ',
    appId: '1:590884738429:web:d39db21c6054629ce6a814',
    messagingSenderId: '590884738429',
    projectId: 'itransit-2-99b65',
    authDomain: 'itransit-2-99b65.firebaseapp.com',
    storageBucket: 'itransit-2-99b65.firebasestorage.app',
    measurementId: 'G-7T39DHTDMC',
  );
}
